// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebDevsuDatabase.Data;

#nullable disable

namespace WebDevsuDatabase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebDevsuDatabase.Models.Entidades.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("direccion");

                    b.Property<bool?>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechaCreacion");

                    b.Property<DateTime?>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fechaNacimiento");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("genero");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numeroIdentificacion");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("WebDevsuDatabase.Models.Entidades.Cuenta", b =>
                {
                    b.Property<int>("IdCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idCuenta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuenta"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<int?>("IdCliente")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("idCliente");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numeroCuenta");

                    b.Property<decimal?>("SaldoInicial")
                        .HasColumnType("numeric")
                        .HasColumnName("saldoInicial");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tipoCuenta");

                    b.HasKey("IdCuenta");

                    b.ToTable("cuenta", (string)null);
                });

            modelBuilder.Entity("WebDevsuDatabase.Models.Entidades.Movimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idMovimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimiento"));

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdCuenta")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("idCuenta");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("tipoMovimiento");

                    b.Property<decimal?>("Valor")
                        .IsRequired()
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("IdMovimiento");

                    b.ToTable("movimiento", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
